name: Release Packaging

on:
  push:
    tags:
    - '*'

permissions:
  contents: write  #  for release creation (svenstaro/upload-release-action)

jobs:
  linux:
    name: Linux AppImages
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@v6

      - name: Install .NET 6.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '6.0.x'

      - name: Prepare Environment
        run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> ${GITHUB_ENV}

      - name: Package AppImage
        run: |
          make engine
          mkdir -p build/linux
          sudo apt-get install -y desktop-file-utils
          ./packaging/linux/buildpackage.sh "${GIT_TAG}" "${PWD}/build/linux"

      - name: Upload Packages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release upload ${{ github.ref_name }} build/linux/*

  windows:
    name: Windows Installers
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@v6

      - name: Install .NET 6.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '6.0.x'

      - name: Prepare Environment
        run: |
          echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> ${GITHUB_ENV}
          sudo apt-get update
          sudo apt-get install nsis wine64

      - name: Package Installers
        run: |
          make engine
          mkdir -p build/windows
          ./packaging/windows/buildpackage.sh "${GIT_TAG}" "${PWD}/build/windows"

      - name: Upload Packages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release upload ${{ github.ref_name }} build/windows/*
